ex# 새 섹션

In [ ]:
ex_list = []
print(ex_list)

[]


In [ ]:
ex_list.append(1)
print(ex_list)

[1]


In [ ]:
ex_list.append(2)
ex_list.append(3)
ex_list.append(4)
ex_list.append(5)
ex_list.append(6)
print(ex_list)

[1, 2, 3, 4, 5, 6]


In [ ]:
ex_list.append('Apple')
print(ex_list)

[1, 2, 3, 4, 5, 6, 'Apple']


In [ ]:
ex_list.append([])
print(ex_list)

[1, 2, 3, 4, 5, 6, 'Apple', []]


In [ ]:
len(ex_list)

8

In [ ]:
ex_list[0]

1

In [ ]:
ex_list[5]

6

In [ ]:
ex_list[7]

[]

In [ ]:
ex_list[7].append(0.9994747)
ex_list[7].append(100.7777)
ex_list


[1, 2, 3, 4, 5, 6, 'Apple', [0.9994747, 100.7777]]

In [ ]:
ex_dict = {}
ex_dict['첫번째'] = 1
print(ex_dict)

{'첫번째': 1}


In [ ]:
ex_dict['딸깍'] = '마우스'
ex_dict

{'딸깍': '마우스', '첫번째': 1}

In [ ]:
# 도
music_note_01 = {}
music_note_01['pitch'] = 60 
music_note_01['length'] = 1.
music_note_01['velocity'] = 100
music_note_01['start_time'] = 0.
# 레
music_note_02 = {}
music_note_02['pitch'] = 62 
music_note_02['length'] = 1.
music_note_02['velocity'] = 100
music_note_02['start_time'] = 1.
# 미
music_note_03 = {}
music_note_03['pitch'] = 64 
music_note_03['length'] = 1.
music_note_03['velocity'] = 100
music_note_03['start_time'] = 2.
note_list = [music_note_01, music_note_02, music_note_03]
# ------------------------------------------------
note_list = [
    {'pitch': 60, 'length':1., 'velocity':100, 'start_time': 0.,}, # 도
    {'pitch': 62, 'length':1., 'velocity':100, 'start_time': 1.,}, # 레
    {'pitch': 64, 'length':1., 'velocity':100, 'start_time': 2.,}, # 미
]


In [ ]:
!pip install midiutil

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.0 MB 5.1 MB/s 
  Created wheel for midiutil: filename=MIDIUtil-1.2.1-py3-none-any.whl size=54566 sha256=2fbd7fea3f466d1779255fe3abd7221b3e99f22708e0c91674a2dee7fb241cf9
  Stored in directory: /root/.cache/pip/wheels/e3/97/cd/a677b61a76d575f373e2e10302f1d9106507fea6dd1320df03
Successfully built midiutil


In [ ]:
import midiutil
def write_midi(seq, bpm, path):
    mf = midiutil.MIDIFile(1, file_format=1)
    track = 0
    channel = 0
    mf.addTempo(track, 0, bpm)
    # for i, n in enumerate(seq):
    for i in range(len(seq)):
        n = seq[i]
        mf.addNote(
            track,
            channel,
            int(n['pitch']),
            n['start_time'],
            n['length'],
            int(n['velocity'])
        )
    with open(path, 'wb') as outf:
        mf.writeFile(outf)

In [ ]:
track_1 = []
track_2 = []

note_1 = {}
note_1['pitch'] = 60
note_1['start_time'] = 0.
note_1['length'] = 4.0
note_1['velocity'] = 100
track_1.append(note_1)

note_2 = {}
note_2['pitch'] = 72
note_2['start_time'] = 4.
note_2['length'] = 4.0
note_2['velocity'] = 100
track_2.append(note_2)


mf = midiutil.MIDIFile(2)
# for i, n in enumerate(seq):
mf.addNote(
    0,
    0,
    int(note_1['pitch']),
    note_1['start_time'],
    note_1['length'],
    int(note_1['velocity'])
)
mf.addNote(
    1,
    0,
    int(note_2['pitch']),
    note_2['start_time'],
    note_2['length'],
    int(note_2['velocity'])
)
with open('multi_track_test.mid', 'wb') as outf:
    mf.writeFile(outf)


In [ ]:
write_midi(seq=note_list, bpm=90, path='output.mid')

In [ ]:
# C - G - Am - Em

C = [
     {'pitch': 60, 'length': 4.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 64, 'length': 4.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 67, 'length': 4.0, 'start_time': 0., 'velocity': 80},
]
G = []
Am = []
Em = []
chord_list = C + G + Am + Em

In [ ]:
ex_list = [1,2,3]
ex_list2 = [4,5,6]

print(ex_list + ex_list2)


[1, 2, 3, 4, 5, 6]


In [ ]:
ex_list3 = [1, 2, 3, 4]
print(ex_list3[3])
ex_list3[3] = 100
C4 = {
    'pitch': 60
}
C4['pitch'] = 72
print(C4)

4
{'pitch': 72}


In [ ]:
dim_1_list = [1, 2, 3, 4] # 1차원리스트

In [ ]:
#.  1 2 3
#.  4 5 6
#.  7 8 9
mat_01 = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
]
for m in mat_01:
  print(m)
print(mat_01[1][2])
mat_01[1][2] = -6

for m in mat_01:
  print(m)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
6
[1, 2, 3]
[4, 5, -6]
[7, 8, 9]


In [ ]:
C = [
     {'pitch': 60,   'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 60+4, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 60+7, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
Dm = [
     {'pitch': 62,   'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 62+3, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 62+7, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
Em = [
     {'pitch': 64,   'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 64+3, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 64+7, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
F = [
     {'pitch': 65   - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 65+4 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 65+7 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
G = [
     {'pitch': 67   - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 67+4 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 67+7 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
Am = [
     {'pitch': 69   - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 69+3 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
     {'pitch': 69+7 - 12, 'length': 1.0, 'start_time': 0., 'velocity': 80},
]
# Bdim = []
chord_group = [
    [C, Em, Am],  # 0: Tonic           
    [F, Dm],  # 1: SubD           
    [G],  # 2: Dom           
]

In [ ]:
import numpy
a = ['a', 'b', 'c']
p = [0.7, 0.2, 0.1]
print(numpy.random.choice(a, 1, p=p))

['b']


In [ ]:
# 0: Tonic Group (1, 3, 6)
# 1: SubDominant Group (2, 4)
# 2: Dominant Group (5, *7)
mm = [
  [0.25, 0.25, 0.50,], # 0 : 토닉
  [0.30, 0.20, 0.50,], # 1 : 섭도
  [0.70, 0.00, 0.30,], # 2 : 도미
]
start = 0. # Tonic 

In [ ]:
import numpy
num_of_chords = 20
state_progression = [0]
for _ in range(num_of_chords):
    current_state = state_progression[-1]
    probs = mm[current_state]
    next_state = numpy.random.choice([0, 1, 2], 
                                     1, 
                                     p=probs)[0]
    state_progression.append(next_state)
state_progression

[0, 0, 1, 1, 2, 2, 0, 2, 2, 0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0]

In [ ]:
def generate_chord_group_progression(step, start_state):
    mm = [
        [0.25, 0.25, 0.50,], # 0 : 토닉
        [0.30, 0.20, 0.50,], # 1 : 섭도
        [0.70, 0.00, 0.30,], # 2 : 도미
    ]
    state_progression = [start_state]
    for _ in range(step):
        current_state = state_progression[-1]
        probs = mm[current_state]
        next_state = numpy.random.choice([0, 1, 2], 
                                        1, 
                                        p=probs)[0]
        state_progression.append(next_state)
    return state_progression

In [ ]:
generate_chord_group_progression(10, 0)

[0, 0, 0, 2, 2, 0, 1, 2, 0, 1, 1]

In [ ]:
test_list = [4, 6, 8, 4, 5]
print(test_list[-1])
print(test_list[len(test_list) - 1])

5
5


In [ ]:
a = ['a', 'b', 'c']
for i in a:
  print(i)

a
b
c


In [ ]:
for i in range(len(a)):
  j = a[i]
  print(i, j)

0 a
1 b
2 c


In [ ]:
a = ['a', 'b', 'c']
for i, j in enumerate(a):
  print(i, j)

0 a
1 b
2 c


In [ ]:
import random
chord_group = [
    [C, Em, Am],  # 0: Tonic           
    [F, Dm],  # 1: SubD           
    [G],  # 2: Dom           
]
chord_progression = []
# [0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 0]
# for i, state in enumerate(state_progression):
for i in range(len(state_progression)):
  state = state_progression[i]
  chord_candidate = chord_group[state]
  chord_pick = random.choice(chord_candidate)  # random.choice(리스트) 리스트안에서 아이템 1개를 랜덤으로 뽑는다.
  start_time = i * 4.0
  for chord_note in chord_pick:
    note_copy = chord_note.copy()
    note_copy['start_time'] = start_time
    note_copy['length'] = 4.0
    chord_progression.append(note_copy)
print(chord_progression)
  
write_midi(chord_progression, 120, 'chord_prog.mid')

[{'pitch': 64, 'length': 4.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 67, 'length': 4.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 71, 'length': 4.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 57, 'length': 4.0, 'start_time': 4.0, 'velocity': 80}, {'pitch': 60, 'length': 4.0, 'start_time': 4.0, 'velocity': 80}, {'pitch': 64, 'length': 4.0, 'start_time': 4.0, 'velocity': 80}, {'pitch': 62, 'length': 4.0, 'start_time': 8.0, 'velocity': 80}, {'pitch': 65, 'length': 4.0, 'start_time': 8.0, 'velocity': 80}, {'pitch': 69, 'length': 4.0, 'start_time': 8.0, 'velocity': 80}, {'pitch': 62, 'length': 4.0, 'start_time': 12.0, 'velocity': 80}, {'pitch': 65, 'length': 4.0, 'start_time': 12.0, 'velocity': 80}, {'pitch': 69, 'length': 4.0, 'start_time': 12.0, 'velocity': 80}, {'pitch': 55, 'length': 4.0, 'start_time': 16.0, 'velocity': 80}, {'pitch': 59, 'length': 4.0, 'start_time': 16.0, 'velocity': 80}, {'pitch': 62, 'length': 4.0, 'start_time': 16.0, 'velocity': 80}, {'pitch': 55, 'len

In [ ]:
def convert_group_num_to_chord_num(group_progression):
    # group_progression = [0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 0]
    chord_group = [
        [1, 3, 6],  # 0: Tonic           
        [4, 2],  # 1: SubD           
        [5],  # 2: Dom           
    ]
    chord_progression = []
    for i in range(len(group_progression)):
        state = group_progression[i]
        chord_candidate = chord_group[state]
        chord_pick = random.choice(chord_candidate)  # random.choice(리스트) 리스트안에서 아이템 1개를 랜덤으로 뽑는다.
        chord_progression.append(chord_pick)
    return chord_progression

In [ ]:
test_input = [0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 0]
convert_group_num_to_chord_num(test_input)

[1, 5, 6, 4, 5, 3, 5, 5, 1, 2, 3, 5, 1, 6, 4, 5, 3, 1, 3, 5, 6]

In [ ]:
# 코드 구성음을 마음대로 펼치는 알고리즘을 구현해봅시다.
# 음역대는 C3(60)~F4(77)
chord_prog = [C, Am, F, G]
write_midi(
    [{'pitch': 60, 'start_time':0, 'length': 4., 'velocity': 100}],
    100,
    'C.mid'    
)

In [ ]:
# Chord_prog 안에 있는 4개의 코드(안에있는 노트정보도)가 차례로 출력되게 for문을 짜보세요. (2줄)
for i in chord_prog:
    print(i)

[{'pitch': 60, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 64, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 67, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}]
[{'pitch': 57, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 60, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 64, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}]
[{'pitch': 53, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 57, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 60, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}]
[{'pitch': 55, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 59, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}, {'pitch': 62, 'length': 1.0, 'start_time': 0.0, 'velocity': 80}]


In [ ]:
# 0부터 127까지의 pitch midi number 중 모든 C(0~)를 찾아서 리스트에 저장해보세요. (4줄정도 필요)
my_list = [] # == my_list = list()
# C-2 = 0 
# C-1 = 12
# C0 = 24
# C1 = 36 ......  
for i in range(128):
    if i % 12 == 0:
        my_list.append(i)

my_list = []
for i in range(0, 128, 12):
    my_list.append(i)

In [69]:
c_maj_scale = [0, 2, 4, 5, 7, 9, 11]
c_maj_pitch_candidate = [
    [], # c
    [], # d
    [], # e
    [], # f
    [], # g
    [], # a
    []  # b
]
# 각 스케일음의 59~F4(77) 범위내 모든 옥타브 pitch를 찾아서 위의 c_maj_scale_all_oct 안에 넣어주세요.
# ** pitch 탐색 범위는 추후 조정될 수 있습니다.
# ** 7번 코드를 복붙할 수도 있지만 for문을 사용해서 효과적으로 작동하도록 해보세요.
min_pitch = 59
max_pitch = 77
for i in range(7):
    for p in range(min_pitch, max_pitch+1):
        if p%12 == c_maj_scale[i]: 
            c_maj_pitch_candidate[i].append(p)
c_maj_pitch_candidate

# # C
# for p in range(59, 77+1):
#    if p%12 == 0: 
#        c_maj_pitch_candidate[0].append(p)
# # D
# for p in range(59, 77+1):
#    if p%12 == 2: 
#        c_maj_pitch_candidate[1].append(p)

# # C
# for p in range(60, 77+1, 12):
#     c_maj_pitch_candidate[0].append(p)
# # D
# for p in range(62, 77+1, 12):
#     c_maj_pitch_candidate[1].append(p)

# ...
# # B
# for p in range(71, 77+1, 12):
#     c_maj_pitch_candidate[1].append(p)



[[60, 72], [62, 74], [64, 76], [65, 77], [67], [69], [59, 71]]

In [ ]:
voicing_candidate_C = [
    c_maj_pitch_candidate[0],  # [0] 도의 보이싱 후보 음들
    c_maj_pitch_candidate[2],  # [1] 미의 보이싱 후보 음들
    c_maj_pitch_candidate[4],  # [2] 솔의 보이싱 후보 음들
]
voicing_candidate_C
# 위에 코드 기능이 이해되시는 분은 C, Dm, Em, F, G, Am에 대해서 모두 만들어주세요.
voicing_candidate_Dm = [
    c_maj_pitch_candidate[1],  # 레의 보이싱 후보 음들
    c_maj_pitch_candidate[3],  # 파의 보이싱 후보 음들
    c_maj_pitch_candidate[5],  # 라의 보이싱 후보 음들
]
voicing_candidate_Em = [
    c_maj_pitch_candidate[2],  # 미의 보이싱 후보 음들
    c_maj_pitch_candidate[4],  # 솔의 보이싱 후보 음들
    c_maj_pitch_candidate[6],  # 시의 보이싱 후보 음들
]
voicing_candidate_F = [
    c_maj_pitch_candidate[3],  # 파의 보이싱 후보 음들
    c_maj_pitch_candidate[5],  # 라의 보이싱 후보 음들
    c_maj_pitch_candidate[0],  # 도의 보이싱 후보 음들
]
voicing_candidate_G = [
    c_maj_pitch_candidate[4],  # 솔의 보이싱 후보 음들
    c_maj_pitch_candidate[6],  # 시의 보이싱 후보 음들
    c_maj_pitch_candidate[1],  # 레의 보이싱 후보 음들
]
voicing_candidate_Am = [
    c_maj_pitch_candidate[5],  # 라의 보이싱 후보 음들
    c_maj_pitch_candidate[0],  # 도의 보이싱 후보 음들
    c_maj_pitch_candidate[2],  # 미의 보이싱 후보 음들
]
print(voicing_candidate_C)
print(voicing_candidate_Dm)
print(voicing_candidate_Em)
print(voicing_candidate_F)
print(voicing_candidate_G)
print(voicing_candidate_Am)


[[60, 72], [64, 76], [67]]
[[62, 74], [65, 77], [69]]
[[64, 76], [67], [59, 71]]
[[65, 77], [69], [60, 72]]
[[67], [59, 71], [62, 74]]
[[69], [60, 72], [64, 76]]


In [ ]:
cmaj_scale_diatonic_chords = [
    None, 
    C,  # [1] I  : C
    Dm, # [2] II : Dm
    Em, # [3] III: Em
    F,  # [4] IV : F
    G,  # [5] V  : G
    Am  # [6] VI : Am
]
cmaj_scale_diatonic_chords_vc = [
    None,
    voicing_candidate_C, # [1] I  : C
    voicing_candidate_Dm,# [2] II : Dm
    voicing_candidate_Em,# [3] III: Em
    voicing_candidate_F, # [4] IV : F
    voicing_candidate_G, # [5] V  : G
    voicing_candidate_Am,# [6] VI : Am
]
cmaj_scale_diatonic_chords_vc[1][0][0]

chord_prog_num = [1, 6, 4, 5]  # C-Am-F-G
# chord_prog_num의 각 코드의 보이싱 후보음들 중에서 랜덤으로 선택해서 최종 음을 선택하게 코드를 구성하시오.
# 예) 
# C에서 voicing_candidate_C[0] 은 도의 보이싱 후보 음들
# C에서 voicing_candidate_C[1] 은 미의 보이싱 후보 음들
# C에서 voicing_candidate_C[2] 은 솔의 보이싱 후보 음들
# random.choice(voicing_candidate_C[0])을 하면 도의 후보음들 중에서 랜덤으로 하나를 선택함
# 코드 노트를 추가하는 방법은 새로운 딕셔너리를 생성해서 그안에 pitch, length, start_time, velocity를 
# 부여하고 최종결과물 리스트에 append 한다. pitch는 랜덤으로 선택한 위의 음을 부여한다.

# cmaj_scale_diatonic_chords_vc: Cmaj 스케일의 3화음의 
chord_prog_number = [1, 6, 4, 5]
voicing_result = []
# for i, chord_num in enumerate(chord_prog_number):
for i in range(len(chord_prog_number)):
    chord_num = chord_prog_number[i]
    start_time = i * 4.0 # 4/4박자 기준 1마디는 4.0 
    voicing_candidate_group = cmaj_scale_diatonic_chords_vc[chord_num] 
    for j in range(len(voicing_candidate_group)):
        voicing_candidate = voicing_candidate_group[j]
        new_note = {}
        new_note['pitch'] = random.choice(voicing_candidate)
        new_note['length'] = 4.0
        new_note['start_time'] = start_time # + random.uniform(-1/16., 1/16.) #   1/16 = 64분음표 길이
        new_note['velocity'] = 70 + random.uniform(-10, 10)
        voicing_result.append(new_note)
write_midi(voicing_result, 120, 'voicing_test.mid')

In [ ]:
def generate_pitch_candidate(scale_list, min_pitch, max_pitch):
    pitch_candidate = [[] for _ in range(7)]
    for i in range(7):
        for p in range(min_pitch, max_pitch+1):
            if p%12 == scale_list[i]: 
                pitch_candidate[i].append(p)
    return pitch_candidate

In [ ]:
pitch_candidate = generate_pitch_candidate([0, 2, 4, 5, 7, 9, 11], 55, 80)

In [ ]:
voicig_candidate_group = []
for i in range(7):
    voicig_candidate_group.append([])
    for j in range(3):
        voicig_candidate_group[-1].append(pitch_candidate[(i + (j*2)) % 7])
voicig_candidate_group

[[[60, 72], [64, 76], [55, 67, 79]],
 [[62, 74], [65, 77], [57, 69]],
 [[64, 76], [55, 67, 79], [59, 71]],
 [[65, 77], [57, 69], [60, 72]],
 [[55, 67, 79], [59, 71], [62, 74]],
 [[57, 69], [60, 72], [64, 76]],
 [[59, 71], [62, 74], [65, 77]]]

In [ ]:
def voicing_chord_progression(chord_num_progression, pitch_candidate, seventh, length):
    voicig_candidate_group = [None,]
    if seventh == True:
        n = 4
    else:
        n = 3
    for i in range(7):
        voicig_candidate_group.append([])
        for j in range(n):
            voicig_candidate_group[-1].append(pitch_candidate[(i + (j*2)) % 7])
    voicing_result = []
    for i in range(len(chord_num_progression)):
        chord_num = chord_num_progression[i]
        start_time = i * length # 4/4박자 기준 1마디는 4.0 
        voicing_candidate_group = voicig_candidate_group[chord_num] 
        for j in range(len(voicing_candidate_group)):
            voicing_candidate = voicing_candidate_group[j]
            new_note = {}
            new_note['pitch'] = random.choice(voicing_candidate)
            new_note['length'] = length
            new_note['start_time'] = start_time # + random.uniform(-1/16., 1/16.) #   1/16 = 64분음표 길이
            new_note['velocity'] = 70 
            voicing_result.append(new_note)
    return voicing_result 

In [61]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os

# Step 1. 코드그룹 진행 생성
chord_group_prog = generate_chord_group_progression(10, 0)
# Step 2. 코드그룹 숫자 -> 코드숫자로 변환
chord_num_prog = convert_group_num_to_chord_num(chord_group_prog)
# Step 3. 보이싱에 사용 가능한 노트집합 생성
p_candidate = generate_pitch_candidate([0, 2, 4, 5, 7, 9, 11], 50, 80)
# Step 4. 랜덤 코드 보이싱 
voicing_result = voicing_chord_progression(chord_num_prog, p_candidate, True, 2.0)
# step 5. 미디파일로 결과 저장


# 구글드라이브안에 폴더는 직접 만들어주셔야 합니다.
dest_path = os.path.join('drive', 'MyDrive', '데이터', 'chord_voicing3.mid')
write_midi(voicing_result, 120, dest_path)

In [ ]:
# for문을 이용해서 N개의 랜덤코드보이싱 미디파일이 생성되게 만들어주세요
# 생성한 미디파일을 한번에 받기위해 각자 구글드라이브를 마운트한후 특정 폴더 안에 모이게 해주세요

In [ ]:
for i in range(10):
    # Step 1. 코드그룹 진행 생성
    chord_group_prog = generate_chord_group_progression(7, random.randint(0, 2))
    # Step 2. 코드그룹 숫자 -> 코드숫자로 변환
    chord_num_prog = convert_group_num_to_chord_num(chord_group_prog)
    # Step 3. 보이싱에 사용 가능한 노트집합 생성
    p_candidate = generate_pitch_candidate([0, 2, 4, 5, 7, 9, 11], 50, 80)
    # Step 4. 랜덤 코드 보이싱 
    voicing_result = voicing_chord_progression(chord_num_prog, p_candidate, True, 2.0)
    # step 5. 미디파일로 결과 저장
    dest_path = os.path.join('drive', 'MyDrive', '데이터', 
                             'chord_voicing_' + str(i).zfill(3) + '.mid')
    write_midi(voicing_result, 120, dest_path)

In [60]:
# !pip install mido
import mido

def read_midi_file(midi_file_path, ticks_per_beat=960):
    # print('midi_file_path', midi_file_path)
    mid = mido.MidiFile(midi_file_path, ticks_per_beat=ticks_per_beat)
    note_temp = []
    note_import = []
    tick = 0
    for i, track in enumerate(mid.tracks):
        for msg in track:
            tick += msg.time
            if msg.type == 'note_on' or msg.type == 'note_off':
                if msg.type == 'note_on':
                    pitch = msg.note
                    start = tick / float(mid.ticks_per_beat)
#                     start = float("{:.4f}".format(start))  # 시간 퀀타이즈
                    velocity = msg.velocity
                    note_info = {
                        'pitch': pitch,
                        'start_time': start,
                        'length': None,
                        'velocity': velocity,
#                         'function': None,
                    }
                    note_temp.append(note_info)
                elif msg.type == 'note_off':
                    for j in range(len(note_temp)):
                        if note_temp[j]['pitch'] == msg.note:
                            end = tick / float(mid.ticks_per_beat)
                            note_temp[j]['length'] = end - note_temp[j]['start_time']
                            note_import.append(note_temp[j])
                            del note_temp[j]
                            break
            else:
                pass
                # print(msg)

    note_import = sorted(note_import, key=lambda k: k['start_time'])
    return note_import

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 51 kB 3.0 MB/s 


In [62]:
# 폴더안의 모든 미디파일 읽어오기
midifile_path = '/content/drive/MyDrive/데이터/chord_voicing_002.mid' # 각자 다름
read_midi_file(midifile_path)

[{'length': 2.0, 'pitch': 79, 'start_time': 0.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 71, 'start_time': 0.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 50, 'start_time': 0.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 77, 'start_time': 0.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 60, 'start_time': 2.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 76, 'start_time': 2.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 79, 'start_time': 2.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 59, 'start_time': 2.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 76, 'start_time': 4.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 79, 'start_time': 4.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 71, 'start_time': 4.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 74, 'start_time': 4.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 67, 'start_time': 6.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 59, 'start_time': 6.0, 'velocity': 70},
 {'length': 2.0, 'pitch': 62, 'start_time': 6.0, 'velocity': 70},
 {'length'

In [77]:
import glob
import os
midifile_folder_path = '/content/drive/MyDrive/데이터'
all_midi_files = glob.glob(os.path.join(midifile_folder_path, '*.mid'))

In [78]:
note_seq_list = []
for i in range(len(all_midi_files)):
    # print(all_midi_files[i])
    note_seq_list.append(read_midi_file(all_midi_files[i]))
    # print(note_seq_list[i])
    # print(note_seq_list[-1])

/content/drive/MyDrive/데이터/chord_voicing_000.mid
[{'pitch': 52, 'start_time': 0.0, 'length': 2.0, 'velocity': 70}, {'pitch': 55, 'start_time': 0.0, 'length': 2.0, 'velocity': 70}, {'pitch': 59, 'start_time': 0.0, 'length': 2.0, 'velocity': 70}, {'pitch': 50, 'start_time': 0.0, 'length': 2.0, 'velocity': 70}, {'pitch': 53, 'start_time': 2.0, 'length': 2.0, 'velocity': 70}, {'pitch': 69, 'start_time': 2.0, 'length': 2.0, 'velocity': 70}, {'pitch': 72, 'start_time': 2.0, 'length': 2.0, 'velocity': 70}, {'pitch': 52, 'start_time': 2.0, 'length': 2.0, 'velocity': 70}, {'pitch': 67, 'start_time': 4.0, 'length': 2.0, 'velocity': 70}, {'pitch': 59, 'start_time': 4.0, 'length': 2.0, 'velocity': 70}, {'pitch': 74, 'start_time': 4.0, 'length': 2.0, 'velocity': 70}, {'pitch': 77, 'start_time': 4.0, 'length': 2.0, 'velocity': 70}, {'pitch': 69, 'start_time': 6.0, 'length': 2.0, 'velocity': 70}, {'pitch': 60, 'start_time': 6.0, 'length': 2.0, 'velocity': 70}, {'pitch': 76, 'start_time': 6.0, 'len

In [79]:
# Encoding
pitch_range = [0, 127]
time_step = 8
single_data = numpy.zeros((time_step, 127 + 1))
print(single_data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [82]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [83]:
pick_seq = note_seq_list[0]
for i in range(len(pick_seq)):
    note = pick_seq[i]
    t_idx = int(note['start_time'] / 2.0)
    p_idx = note['pitch']
    single_data[t_idx][p_idx] = 1
print(single_data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.

In [88]:
train_x = []
for i in range(len(note_seq_list)):
    note_seq = note_seq_list[i]
    single_data = numpy.zeros((time_step, 127 + 1))
    for j in range(len(note_seq)):
        note = note_seq[j]
        t_idx = int(note['start_time'] / 2.0)
        p_idx = note['pitch']
        single_data[t_idx][p_idx] = 1
    train_x.append(single_data)
    
print(numpy.array(train_x).shape)

(10, 8, 128)


In [94]:
# good과 bad 데이터를 읽어서 라벨링을 같이 불러옵니다.
good_path = '/content/drive/MyDrive/데이터/good'
bad_path = '/content/drive/MyDrive/데이터/bad'
# good에 해당하는 미디데이터 읽기 (Mid파일->노트seq)
good_midi_files = glob.glob(os.path.join(good_path, '*.mid'))
good_note_seq_list = []
for i in range(len(good_midi_files)):
    good_note_seq_list.append(read_midi_file(good_midi_files[i]))
# bad에 해당하는 미디데이터 읽기 (Mid파일->노트seq)
bad_midi_files = glob.glob(os.path.join(bad_path, '*.mid'))
bad_note_seq_list = []
for i in range(len(bad_midi_files)):
    bad_note_seq_list.append(read_midi_file(bad_midi_files[i]))

# AI 학습을 위한 데이터 Encoding (노트seq->many-hot-vectors)
# Good, Encoding!
train_x_good = []
for i in range(len(good_note_seq_list)):
    note_seq = good_note_seq_list[i]
    single_data = numpy.zeros((time_step, 127 + 1))
    for j in range(len(note_seq)):
        note = note_seq[j]
        t_idx = int(note['start_time'] / 2.0)
        p_idx = note['pitch']
        single_data[t_idx][p_idx] = 1
    train_x_good.append(single_data)
# Bad, Encoding!
train_x_bad = []
for i in range(len(bad_note_seq_list)):
    note_seq = bad_note_seq_list[i]
    single_data = numpy.zeros((time_step, 127 + 1))
    for j in range(len(note_seq)):
        note = note_seq[j]
        t_idx = int(note['start_time'] / 2.0)
        p_idx = note['pitch']
        single_data[t_idx][p_idx] = 1
    train_x_bad.append(single_data)

# 아래는 test 데이터를 뽑지 않고 전부 train 데이터로 할당했음.
# train_x = train_x_good + train_x_bad
# # train_y = [1] * len(train_x_good) + [0] * len(train_x_bad)
# train_y = []
# for i in range(len(train_x_good)):
#     train_y.append(1)
# for i in range(len(train_x_bad)):
#     train_y.append(0)

test_x_good = train_x_good[0:int(len(train_x_good)*0.2)]
test_y_good = [1] * len(test_x_good)
train_x_good = train_x_good[int(len(train_x_good)*0.2):]
train_y_good = [1] * len(train_x_good)
test_x_bad = train_x_bad[0:int(len(train_x_bad)*0.2)]
test_y_bad = [0] * len(test_x_bad)
train_x_bad = train_x_bad[int(len(train_x_bad)*0.2):]
train_y_bad = [0] * len(train_x_bad)

train_x = train_x_good + train_x_bad
train_y = train_y_good + train_y_bad

test_x = test_x_good + test_x_bad
test_y = test_y_good + test_y_bad

In [98]:
# numpy로 데이터 변환
train_x = numpy.array(train_x)
train_y = numpy.array(train_y)
test_x = numpy.array(test_x)
test_y = numpy.array(test_y)

In [91]:
%load_ext tensorboard

In [92]:
import tensorflow as tf
import datetime

In [93]:
!rm -rf ./logs/ 

In [96]:
def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(8, 128)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

In [99]:
model = create_model()
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=train_x, 
          y=train_y, 
          epochs=5, 
          validation_data=(test_x, test_y), 
          callbacks=[tensorboard_callback])

Epoch 1/5
1/1 [==============================] - 1s 1s/step - loss: 0.7272 - accuracy: 0.5000 - val_loss: 0.6551 - val_accuracy: 1.0000
Epoch 2/5
1/1 [==============================] - 0s 85ms/step - loss: 0.6948 - accuracy: 0.5000 - val_loss: 0.6666 - val_accuracy: 1.0000
Epoch 3/5
1/1 [==============================] - 0s 85ms/step - loss: 0.6183 - accuracy: 1.0000 - val_loss: 0.6786 - val_accuracy: 1.0000
Epoch 4/5
1/1 [==============================] - 0s 95ms/step - loss: 0.5909 - accuracy: 1.0000 - val_loss: 0.6912 - val_accuracy: 1.0000
Epoch 5/5
1/1 [==============================] - 0s 103ms/step - loss: 0.5392 - accuracy: 1.0000 - val_loss: 0.7039 - val_accuracy: 0.0000e+00


In [ ]:
%tensorboard --logdir logs/fit